let ratio1=[
    {
        "name":"鮮乳(含保久乳)","count":58.6
    },
    {
        "name":"調味乳","count":14.7
    },
    {
        "name":"發酵乳","count":11.6
    },
    {
        "name":"冰淇淋","count":8.6
    },
    {
        "name":"其他乳製品","count":6.7
    }
];
let ratio2=[
    {
        "name":"鮮乳(含保久乳)","count":59.8
    },
    {
        "name":"調味乳","count":15.2
    },
    {
        "name":"發酵乳","count":11.8
    },
    {
        "name":"冰淇淋","count":6.8
    },
    {
        "name":"其他乳製品","count":6.4
    }
];
let ratio3=[
    {
        "name":"鮮乳(含保久乳)","count":59.8
    },
    {
        "name":"調味乳","count":15.4
    },
    {
        "name":"發酵乳","count":12.7
    },
    {
        "name":"冰淇淋","count":6.0
    },
    {
        "name":"其他乳製品","count":6.1
    }
];
let ratio4=[
    {
        "name":"鮮乳(含保久乳)","count":58.7
    },
    {
        "name":"調味乳","count":16.1
    },
    {
        "name":"發酵乳","count":12.9
    },
    {
        "name":"冰淇淋","count":6.3
    },
    {
        "name":"其他乳製品","count":6.0
    }
];